# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
string="hi there sam!"
print(string.split())

['hi', 'there', 'sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [3]:
planet="earth"
diameter=12742
'The diameter of {} is {} kilometers.'.format(planet,diameter)
'The diameter of earth is 12742 kilometers.'


'The diameter of earth is 12742 kilometers.'

## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d['k1'][3]['tricky'][3]['target'][3]


'hello'

# Numpy

In [9]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [13]:
print(np.arange(20,36,2))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [25]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
arr=np.concatenate((a,b))

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [30]:
import pandas as pd


In [31]:
df=pd.DataFrame({'X':[0,1,2],'Y':[3,4,5]},index=['A','B','C'])
print(df)
print(df.T)

   X  Y
A  0  3
B  1  4
C  2  5
   A  B  C
X  0  1  2
Y  3  4  5


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [38]:
import pandas as pd 
from dateutil.parser import parse 
date_series=pd.Series(['Jan 2015', 'Feb 2016','Mar 2017','Apr 2018','May 2019'])
print("Original Series:")
print(date_series)
print("\nNew dates:")
result= date_series.map(lambda d: parse('11'+ d))
print(result)

Original Series:
0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: object

New dates:
0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [22]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [35]:
df = pd.DataFrame( columns = ['category','name','marks'])
print(df)

Empty DataFrame
Columns: [category, name, marks]
Index: []
